POST http://localhost:8080/auth/connect
Content-Type: application/json

{"data": {"username":"TI_BHM_loris", "password":"VILA"}}


###
POST http://localhost:8080/auth/checkToken
Content-Type: application/json

{"data": {"token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRJX0JITV9sb3JpcyIsImlhdCI6MTcwNzUxODg5OSwiZXhwIjoxNzA3OTUwODk5fQ.jzoTq-IF-RbO8XiadklkPOHv48-khoukut810Sb22Lk"}}

###
GET http://localhost:8081/auth/users
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXhhbmRyZSIsImlhdCI6MTcyMTgwMDg5OCwiZXhwIjoxNzIyMjMyODk4fQ.5lHQf7N1T1H5OrID_Mci6W9FLewj7iUHCW-mqeWgVfs

###
POST http://localhost:8081/dataManage/createDocument
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjA0MDAxNTJZIiwiaWF0IjoxNzIyNDUzODc2LCJleHAiOjE3MjI4ODU4NzZ9.X2NZ2iPSMYFtuB220ABw3ppKgkig7CReaK1zPtcNgv8",
    "data": {
        "document": {
            "name": "sqd",
            "ref_main": "qsd",
            "page": "ld",
            "engin": "AGC",
            "engin_type": [
                "XGC"
            ],
            "meta": [],
            "tags": [],
            "links": []
        }
    }
}
